name: Run main.py

on:
  schedule:
    # Schedule the script to run every day at 9:00 AM UTC
    - cron: "40 2 * * 1-5"
  workflow_dispatch: # Allow manual trigger of the workflow
  push:
    branches:
      - main  # Trigger when the main branch is updated

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # Specify the Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the main script
      - name: Run main.py
        env:
          ZOHO_CLIENT_ID: ${{ secrets.ZOHO_CLIENT_ID }}
          ZOHO_CLIENT_SECRET: ${{ secrets.ZOHO_CLIENT_SECRET }}
          ZOHO_REDIRECT_URI: ${{ secrets.ZOHO_REDIRECT_URI }}
          ZOHO_REFRESH_TOKEN: ${{ secrets.ZOHO_REFRESH_TOKEN }}
        run: python main.py
